//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_SERVER.DataBase.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARMOR()
        {
            this.ELEMENT_OF_ARMOR = new HashSet<ELEMENT_OF_ARMOR>();
        }
    
        public int ID { get; set; }
        public int ARMOR_TYPE_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ARMOR_TYPE ARMOR_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELEMENT_OF_ARMOR> ELEMENT_OF_ARMOR { get; set; }
    }
}
