//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_SERVER.DataBase.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMOR_DEFENCE_VIEW
    {
        public string NAME { get; set; }
        public Nullable<int> DEFENCE { get; set; }
        public int ARMOR_TYPE_ID { get; set; }
    }
}
