//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_SERVER.DataBase.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseContext : DbContext
    {
        public DataBaseContext()
            : base("name=DataBaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARMOR> ARMOR { get; set; }
        public virtual DbSet<ARMOR_TYPE> ARMOR_TYPE { get; set; }
        public virtual DbSet<ELEMENT_OF_ARMOR> ELEMENT_OF_ARMOR { get; set; }
        public virtual DbSet<PART_OF_ARMOR> PART_OF_ARMOR { get; set; }
        public virtual DbSet<ARMOR_DEFENCE_VIEW> ARMOR_DEFENCE_VIEW { get; set; }
    }
}
