//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_SERVER.DataBase.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class ELEMENT_OF_ARMOR
    {
        public int ID { get; set; }
        public string DEV_ID { get; set; }
        public int PART_ID { get; set; }
        public int ARMOR_ID { get; set; }
        public string NAME { get; set; }
        public string IMG_URL { get; set; }
        public double WEIGHT { get; set; }
        public int DEFENCE { get; set; }
        public int PRICE { get; set; }
        [JsonIgnore]
        public virtual ARMOR ARMOR { get; set; }
        [JsonIgnore]
        public virtual PART_OF_ARMOR PART_OF_ARMOR { get; set; }
    }
}
